name: Rust CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x86_64, aarch64] # 定义架构矩阵

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-code-tester
          path: |
            target/release/code-tester
            target/release/code-tester.exe

      - name: Check if Stable Version
        id: version_check
        run: |
          echo "Tag: ${{ github.ref }}"
          if [[ "${{ github.ref }}" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "is_stable=true" >> $GITHUB_OUTPUT
          else
          echo "is_stable=false" >> $GITHUB_OUTPUT
          fi

      - name: Create or Update Release
        if: steps.version_check.outputs.is_stable == 'true'
        uses: softprops/action-gh-release@v2
        with:
          release_name: Release ${{ github.ref_name }}
          body_path: changelog/${{ github.ref_name }}.md
          draft: false
          prerelease: false
          files: |
            target/release/code-tester
            target/release/code-tester.exe
